// <auto-generated />
using Ecommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description test",
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Rolex_Submariner_Professional.JPG/1280px-Rolex_Submariner_Professional.JPG",
                            Price = 9.99m,
                            Title = "Title Test"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description2",
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/6/67/RolexDaytona.jpg",
                            Price = 3.99m,
                            Title = "Watch2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description3",
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Spring-cover_pocket_clock3_open_clockface2.jpg/1200px-Spring-cover_pocket_clock3_open_clockface2.jpg",
                            Price = 4.99m,
                            Title = "Watch3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
